FROM ubuntu
RUN apt-get update && apt-get install -y \
	wget \
	unzip \
	git

RUN apt-get install -y python3-pip
RUN apt-get install -y python-pip
RUN pip3 --version
RUN pip3 install --upgrade pip
RUN pip3 install numpy
RUN pip3 install opencv-python
RUN pip3 install uwsgi




